name: car
description: Car Maintenance & Fuel Tracker App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.6
  http: ^1.2.1
  flutter_sms_inbox: ^1.0.4
  permission_handler: ^11.3.0

  dropdown_search: ^5.0.6

  
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  
  # State Management
  provider: ^6.1.2
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  
  # Utilities
  intl: ^0.19.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.11.0
  flutter_background: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true