// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDii8BKQksnLGT7TkW5pAttWTk1mD5GgGc',
    appId: '1:365490223161:web:cac1fcadce5993e10075e8',
    messagingSenderId: '365490223161',
    projectId: 'car-app-7872f',
    authDomain: 'car-app-7872f.firebaseapp.com',
    storageBucket: 'car-app-7872f.firebasestorage.app',
    measurementId: 'G-DJKLQYX6SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRnvSRmh28VORXIJOa6vAI9iXVZlxaj10',
    appId: '1:365490223161:android:21035ba5682d57970075e8',
    messagingSenderId: '365490223161',
    projectId: 'car-app-7872f',
    storageBucket: 'car-app-7872f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoIiBTAuTOZ_2PmDTBMn_frPLmxLBDJ1o',
    appId: '1:365490223161:ios:9fcc9bd35306e8580075e8',
    messagingSenderId: '365490223161',
    projectId: 'car-app-7872f',
    storageBucket: 'car-app-7872f.firebasestorage.app',
    iosBundleId: 'com.example.car',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoIiBTAuTOZ_2PmDTBMn_frPLmxLBDJ1o',
    appId: '1:365490223161:ios:9fcc9bd35306e8580075e8',
    messagingSenderId: '365490223161',
    projectId: 'car-app-7872f',
    storageBucket: 'car-app-7872f.firebasestorage.app',
    iosBundleId: 'com.example.car',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDii8BKQksnLGT7TkW5pAttWTk1mD5GgGc',
    appId: '1:365490223161:web:aa5f500cfdc906490075e8',
    messagingSenderId: '365490223161',
    projectId: 'car-app-7872f',
    authDomain: 'car-app-7872f.firebaseapp.com',
    storageBucket: 'car-app-7872f.firebasestorage.app',
    measurementId: 'G-44QGYBFCW3',
  );

}